// export const ROUTES = {
//   welcome: "/",
//   home: "/home",
//   dashboard: "/",
//   products: "/products",
//   productDetail: "/product/:productId",
//   productDetails: (productId: string) => `/products/${productId}`,
//   cart: "/cart",
//   checkout: "/checkout",
//   checkoutSuccess: "/checkout/success",
//   aboutUs: "/about-us",
//   story: "/story",
//   customRequests: "/custom-requests",
//   customRequestSubmitted: "/custom-requests/submitted",
//   customRequestDetails: (requestId: string) => `/custom-requests/${requestId}`,
//   contact: "/contact",
//   search: "/search",
//   notifications: "/notifications",
//   wishlist: "/wishlist",
//   orders: "/orders",
//   signup: "/signup",
//   login: "/login",
//   forgotPassword: "/forgot-password",
//   checkEmail: "/check-email",
//   resetPassword: "/reset-password",
//   otpVerification: "/otp-verification",
//   personalInfo: "/personal-info",
//   profile: "/profile",
//   addresses: "/addresses",
//   orderDetail: "/orders/:orderId",
//   designDetail: "/orders/:orderId/design",
//   help: "/help",
// } as const;


export const ROUTES = {
  welcome: "/",
  home: "/home",
  dashboard: "/dashboard", // تغيير مسار الداشبورد لمنع التعارض مع "/"
  products: "/products",
  productDetail: "/products/:productId", // توحيد الهيكل
  productDetails: (productId: string) => `/products/${productId}`,
  cart: "/cart",
  checkout: "/checkout",
  checkoutSuccess: "/checkout/success",
  aboutUs: "/about-us",
  story: "/story",
  customRequests: "/custom-requests",
  customRequestsNew: "/custom-requests/new",
  customRequestSubmitted: "/custom-requests/submitted",
  customRequestDetail: "/custom-requests/:requestId",
  customRequestDetails: (requestId: string) => `/custom-requests/${requestId}`,
  contact: "/contact",
  search: "/search",
  notifications: "/notifications",
  wishlist: "/wishlist",
  orders: "/orders",
  orderDetail: "/orders/:orderId",
  designDetail: "/orders/:orderId/design",
  signup: "/signup",
  login: "/login",
  forgotPassword: "/forgot-password",
  checkEmail: "/check-email",
  resetPassword: "/reset-password",
  otpVerification: "/otp-verification",
  personalInfo: "/personal-info",
  profile: "/profile",
  addresses: "/addresses",
  help: "/help",
} as const;