export const ROUTES = {
  welcome: "/",
  home: "/home",
  dashboard: "/",
  products: "/products",
  productDetails: (productId: string) => `/products/${productId}`,
  cart: "/cart",
  checkout: "/checkout",
  checkoutSuccess: "/checkout/success",
  aboutUs: "/about-us",
  story: "/story",
  customRequests: "/custom-requests",
  customRequestSubmitted: "/custom-requests/submitted",
  customRequestDetails: (requestId: string) => `/custom-requests/${requestId}`,
  contact: "/contact",
  search: "/search",
  notifications: "/notifications",
  wishlist: "/wishlist",
  orders: "/orders",
  signup: "/signup",
  login: "/login",
  forgotPassword: "/forgot-password",
  checkEmail: "/check-email",
  resetPassword: "/reset-password",
  otpVerification: "/otp-verification",
} as const;
